//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Smart_Trafic_Management_System.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Vehicle_Registration
    {
        public int Vehicle_ID { get; set; }
        [Required]
        public string Manufacturer { get; set; }
        [Required]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> Date_of_Registration { get; set; }
        [Required]
        public string Registration_Number { get; set; }
        [Required]
        public string Model { get; set; }
        [Required]
        public string Remarks { get; set; }
        [Required]
        public string Vehicle_Type { get; set; }
    }
}
